[book]
authors = ["masud"]
language = "en"
multilingual = false
src = "src"
title = "Floresta mdbook"
description = "A book about Floresta, A fully-validating Bitcoin node powered by Utreexo, with an integrated Electrum Server, built in Rust"

[rust]
edition = "2018"

# [output.html]
# smart-punctuation = true
# mathjax-support = true
# site-url = "/mdBook/"
# git-repository-url = "https://github.com/rust-lang/mdBook/tree/master/guide"
# edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"

# [output.html.playground]
# editable = true
# line-numbers = true

# [output.html.code.hidelines]
# python = "~"

# [output.html.search]
# limit-results = 20
# use-boolean-and = true
# boost-title = 2
# boost-hierarchy = 2
# boost-paragraph = 1
# expand = true
# heading-split-level = 2

# [output.html.redirect]
# "/format/config.html" = "configuration/index.html"